config:
  - waypoint_id: registed_0_1258678000000
    map_file: /home/kazuki/tsukuba_ws/src/real_tsudanuma2-3_sim/maps/map2.yaml
  - waypoint_id: registed_0_1361382000000
    map_file: /home/kazuki/tsukuba_ws/src/real_tsudanuma2-3_sim/maps/map1.yaml